server:
  port: 80

spring:
  application:
    name: dao-boot
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      # 全局配置雪花算法
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0